using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Explain
{
    // These classes provide storage for data about the code and comments
    // Generated by the engine and used by the output template
    public class OutputUnit
    {
        public string CodeFile;
        public string Name;
        public List<Section> Sections;
        public string SizeFormatted;
    }

    public class Section
    {
        public string CodeHtml;
        public string DocsHtml;
        public int StartLine;
        public int EndLine;
        public int CodeStartLine;
    }
}
